from gridiron_ml.cli._paths import project_root
#!/usr/bin/env python3
"""Inventory artifacts before cleanup, relocation, or release pruning."""

from argparse import ArgumentParser
from hashlib import sha256
import csv
from pathlib import Path
import os
import subprocess
from typing import Iterable


def file_hash(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def disposition(path: Path) -> tuple[str, str, str]:
    external_root = os.environ.get("TDNET_EXTERNAL_ROOT", "EXTERNAL_DURABLE_ROOT")
    value = path.as_posix()
    suffix = path.suffix.lower()
    if any(token in value for token in ["__pycache__", ".pytest_cache", ".ipynb_checkpoints"]):
        return "remove_replaceable", "", "cache or generated bytecode"
    if value.startswith("models/") and ("checkpoint" in value or suffix in {".pkl", ".pt", ".pth"}):
        return "relocate_durable_retain", f"{external_root}/model_checkpoints/{value}", "large model bytes do not belong in public Git"
    if value.startswith("data/"):
        return "relocate_or_regenerate", f"{external_root}/{value}", "CFBD-derived data are replaceable and should be external"
    if value.startswith("outputs/") or value.startswith("publication/"):
        return "retain_public_compact", value, "canonical publication evidence or compact source data"
    if value.startswith("publication/notebooks/"):
        return "review_archive", f"{external_root}/archives/{value}", "retain history until shared-code replacement is verified"
    if suffix in {".png", ".svg", ".html"}:
        return "deduplicate_after_review", f"{external_root}/archives/{value}", "keep canonical purpose only"
    return "retain_review", value, "requires publication/reproducibility review"


def tracked_files(repo: Path) -> set[str]:
    result = subprocess.run(["git", "ls-files", "-z"], cwd=repo, check=True, capture_output=True)
    return {item.decode() for item in result.stdout.split(b"\0") if item}


def inventory(repo: Path, roots: Iterable[str]) -> list[dict[str, object]]:
    tracked = tracked_files(repo)
    rows = []
    for root in roots:
        base = repo / root
        if not base.exists():
            continue
        for path in sorted(p for p in base.rglob("*") if p.is_file() and not p.is_symlink()):
            relative = path.relative_to(repo).as_posix()
            action, new_path, reason = disposition(Path(relative))
            rows.append({
                "original_path": relative,
                "disposition": action,
                "new_path": new_path,
                "reason": reason,
                "size_bytes": path.stat().st_size,
                "sha256": file_hash(path),
                "git_tracked": relative in tracked,
                "required_for_reproducibility": action not in {"remove_replaceable", "deduplicate_after_review"},
                "included_in_public_release": action == "retain_public_compact",
            })
    return rows


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument("--repo", type=Path, default=project_root())
    parser.add_argument("--roots", nargs="+", default=["data", "models", "outputs", "publication", "notebooks"])
    parser.add_argument("--csv", type=Path, default=None)
    parser.add_argument("--json", type=Path, default=None)
    args = parser.parse_args()
    repo = args.repo.resolve()
    rows = inventory(repo, args.roots)
    csv_path = args.csv or repo / "docs/publication_2026/storage_cleanup_report.csv"
    json_path = args.json or repo / "docs/publication_2026/storage_cleanup_summary.json"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else ["original_path"])
        writer.writeheader()
        writer.writerows(rows)
    summary = {
        "repository": str(repo),
        "roots": list(args.roots),
        "file_count": len(rows),
        "bytes": sum(int(row["size_bytes"]) for row in rows),
        "disposition_counts": {},
        "tracked_count": sum(bool(row["git_tracked"]) for row in rows),
        "csv": str(csv_path),
    }
    for row in rows:
        key = str(row["disposition"])
        summary["disposition_counts"][key] = summary["disposition_counts"].get(key, 0) + 1
    json_path.write_text(__import__("json").dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(__import__("json").dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
